# Generated by Django 5.2.11 on 2026-02-09 11:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('value_format', models.CharField(max_length=50)),
                ('value_char', models.CharField(blank=True, max_length=255, null=True)),
                ('value_num', models.IntegerField(blank=True, null=True)),
                ('value_date', models.DateTimeField(blank=True, null=True)),
                ('type_list', models.CharField(max_length=255)),
                ('source', models.CharField(default='client', max_length=30)),
                ('lock', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
                ('update_at', models.DateTimeField(auto_now=True, db_column='modification_date')),
                ('extern_ref_admin_lov', models.BigIntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('sgbd_password', models.TextField(blank=True, null=True)),
                ('priv_key', models.TextField(blank=True, null=True)),
                ('sgbd_host', models.CharField(max_length=255)),
                ('sgbd_user', models.CharField(blank=True, max_length=255, null=True)),
                ('sgbd_port', models.IntegerField(blank=True, null=True)),
                ('sgbd_driver', models.CharField(blank=True, max_length=255, null=True)),
                ('sgbd_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('sgbd_database', models.CharField(blank=True, max_length=255, null=True)),
                ('sgbd_tls', models.BooleanField(default=False)),
                ('sgbd_x509', models.BooleanField(default=False)),
                ('sgbd_ca_file', models.TextField(blank=True, null=True)),
                ('sgbd_certificate_key_file', models.TextField(blank=True, null=True)),
                ('sgbd_certificate_file', models.TextField(blank=True, null=True)),
                ('sgbd_certificate_key_file_password', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modification_date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sgbd_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sgbd', to='tdm_orchestrator.type')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('siret', models.CharField(blank=True, max_length=255, null=True)),
                ('sigle', models.CharField(blank=True, max_length=255, null=True)),
                ('dpo', models.CharField(blank=True, max_length=255, null=True)),
                ('address_postal', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_dpo', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modification_date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tdm_orchestrator.entity')),
                ('forme_juridique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forme_juridique', to='tdm_orchestrator.type')),
                ('type_entite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tdm_orchestrator.type')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('type2', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('mac_address', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='creation_date')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='modification_date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('data_sources', models.ManyToManyField(blank=True, related_name='application_datasource', to='tdm_orchestrator.datasource')),
                ('entity', models.ManyToManyField(related_name='application_entity', to='tdm_orchestrator.entity')),
                ('type1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tdm_orchestrator.type')),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Refresh Mensuel CRM, Purge Logs Hebdo', max_length=255, verbose_name='Nom du Runner')),
                ('description', models.TextField(blank=True, help_text='Objectif de cet orchestrateur', verbose_name='Description')),
                ('stop_on_error', models.BooleanField(default=True, help_text="Si True, arrête tout dès qu'un script échoue. Si False, continue (Best Effort)", verbose_name="Arrêter en cas d'erreur")),
                ('verbose_logging', models.BooleanField(default=False, help_text='Active les logs détaillés pour le débogage', verbose_name='Logs verbeux')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdm_orchestrator.application', verbose_name='Application cible')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_runners', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Runner (Orchestrateur)',
                'verbose_name_plural': 'Runners (Orchestrateurs)',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SqlScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Disable_FK_CRM, Clean_Audit_Logs', max_length=255, verbose_name='Nom du script')),
                ('description', models.TextField(blank=True, help_text='Explication de ce que fait le script', verbose_name='Description')),
                ('script_type', models.CharField(choices=[('PRE', 'Pre-Processing'), ('POST', 'Post-Processing'), ('UTIL', 'Utility')], default='UTIL', max_length=10, verbose_name='Type de script')),
                ('content', models.TextField(help_text='Le code SQL brut. Supporte les variables comme ${TARGET_SCHEMA}', verbose_name='Contenu SQL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('application', models.ForeignKey(help_text="L'application concernée (CRM, ERP, etc.)", on_delete=django.db.models.deletion.CASCADE, to='tdm_orchestrator.application', verbose_name='Application cible')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scripts', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('datasource', models.ForeignKey(blank=True, help_text='La connexion DB sur laquelle exécuter ce script', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tdm_orchestrator.datasource', verbose_name='Source de données')),
            ],
            options={
                'verbose_name': 'Script SQL',
                'verbose_name_plural': 'Scripts SQL',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunnerStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Position dans la séquence (1, 2, 3...)', validators=[django.core.validators.MinValueValidator(1)], verbose_name="Ordre d'exécution")),
                ('step_type', models.CharField(choices=[('PRE', 'Pre-Process'), ('POST', 'Post-Process')], help_text='Pre-Process ou Post-Process', max_length=10, verbose_name='Phase')),
                ('enabled', models.BooleanField(default=True, help_text='Permet de désactiver temporairement un script sans le supprimer', verbose_name='Activé')),
                ('timeout_seconds', models.PositiveIntegerField(blank=True, help_text="Durée max d'exécution pour ce script spécifiquement", null=True, verbose_name='Timeout (secondes)')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdm_orchestrator.runner', verbose_name='Runner')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdm_orchestrator.sqlscript', verbose_name='Script')),
            ],
            options={
                'verbose_name': 'Étape de Runner',
                'verbose_name_plural': 'Étapes de Runner',
                'ordering': ['step_type', 'order'],
            },
        ),
        migrations.AddField(
            model_name='runner',
            name='scripts',
            field=models.ManyToManyField(related_name='runners', through='tdm_orchestrator.RunnerStep', to='tdm_orchestrator.sqlscript', verbose_name='Scripts associés'),
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('SUCCESS', 'Succès'), ('FAILURE', 'Échec')], default='PENDING', max_length=20)),
                ('logs', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('runner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='tdm_orchestrator.runner')),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='tdm_orchestrator.sqlscript')),
            ],
        ),
        migrations.AddIndex(
            model_name='sqlscript',
            index=models.Index(fields=['script_type'], name='tdm_orchest_script__b3b404_idx'),
        ),
        migrations.AddIndex(
            model_name='sqlscript',
            index=models.Index(fields=['application'], name='tdm_orchest_applica_2e5c1f_idx'),
        ),
        migrations.AddIndex(
            model_name='runnerstep',
            index=models.Index(fields=['runner', 'step_type', 'order'], name='tdm_orchest_runner__42923f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='runnerstep',
            unique_together={('runner', 'script', 'step_type')},
        ),
    ]
